# Generated by Django 4.1 on 2023-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingTokenizableProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=255)),
                ('product_title', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('affiliate_link', models.URLField(max_length=100)),
            ],
            options={
                'db_table': 'trending_tokenizable_products',
            },
        ),
    ]
