# Generated by Django 4.1 on 2023-10-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVerificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('title_id', models.CharField(max_length=200)),
                ('verified_by', models.CharField(max_length=100)),
                ('asset_category', models.IntegerField(choices=[(0, 'Smartphone'), (1, 'Laptop'), (2, 'Tablet'), (3, 'SmartTV'), (4, 'Smartwatch')], default=0)),
                ('verification_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified')], default=0)),
                ('ticker_name', models.CharField(max_length=50, null=True)),
                ('device_name', models.CharField(max_length=50, null=True)),
                ('device_brand', models.CharField(max_length=50, null=True)),
                ('device_uuid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'asset_verification_status',
            },
        ),
        migrations.CreateModel(
            name='TickerNameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('category', models.IntegerField(choices=[(0, 'Smartphone'), (1, 'Laptop'), (2, 'Tablet'), (3, 'SmartTV'), (4, 'Smartwatch')])),
                ('ticker_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ticker_name_data',
            },
        ),
    ]
