# Generated by Django 4.1 on 2023-10-17 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_assetverificationstatus_tickernamedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetverificationstatus',
            name='title_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='AssetMaintenanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_period', models.IntegerField()),
                ('currency_selected', models.CharField(max_length=20)),
                ('premium_in_usd', models.FloatField()),
                ('premium_in_selected_currency', models.FloatField()),
                ('maintenance_applied_on', models.DateField(auto_now_add=True)),
                ('maintenance_started_on', models.DateField(auto_now=True)),
                ('payment_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0)),
                ('title_id', models.ForeignKey(db_column='title_id', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_status', to='asset.assetverificationstatus', to_field='title_id')),
            ],
            options={
                'db_table': 'asset_maintenance_status',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
