# Generated by Django 4.1 on 2023-10-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_assetverificationstatus_title_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assetmaintenancestatus',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='assetverificationstatus',
            name='index_token',
            field=models.IntegerField(null=True),
        ),
    ]
