# Generated by Django 4.1 on 2023-10-20 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_assetmaintenancestatus_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaintenancestatus',
            name='maintenance_expire_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
