# Generated by Django 4.1 on 2023-10-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_assetmaintenancestatus_damage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaintenancestatus',
            name='maintenance_reward_status',
            field=models.IntegerField(choices=[(0, 'Not Claimed'), (1, 'Claim In Progress'), (2, 'Approved'), (3, 'Rejected')], default=0),
        ),
    ]
