# Generated by Django 4.1 on 2023-10-26 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_assetmaintenancestatus_maintenance_reward_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetverificationstatus',
            name='ipfs_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assetmaintenancestatus',
            name='maintenance_expire_on',
            field=models.DateField(default=datetime.date(2023, 10, 26)),
        ),
    ]
