# Generated by Django 4.1 on 2023-10-27 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_assetverificationstatus_ipfs_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('device_category', models.IntegerField(choices=[(0, 'Smartphone'), (1, 'Laptop'), (2, 'Tablet'), (3, 'SmartTV'), (4, 'Smartwatch')])),
                ('price', models.FloatField()),
                ('price_year', models.IntegerField()),
            ],
            options={
                'db_table': 'device_price_data',
            },
        ),
        migrations.AlterField(
            model_name='assetmaintenancestatus',
            name='maintenance_expire_on',
            field=models.DateField(default=datetime.date(2023, 10, 27)),
        ),
    ]
