# Generated by Django 4.2.7 on 2023-11-07 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_devicepricedata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintenancestatus',
            name='maintenance_expire_on',
            field=models.DateField(default=datetime.date(2023, 11, 7)),
        ),
    ]
