# Generated by Django 4.2.7 on 2023-11-08 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_alter_assetmaintenancestatus_maintenance_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintenancestatus',
            name='maintenance_expire_on',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
    ]
