# Generated by Django 4.2.7 on 2023-11-14 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_alter_assetmaintenancestatus_maintenance_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintenancestatus',
            name='maintenance_claim_status',
            field=models.IntegerField(choices=[(0, 'Not Claimed'), (1, 'Rejected'), (2, 'Approved'), (3, 'In Progress'), (4, 'Pre-Approved')], default=0),
        ),
        migrations.AlterField(
            model_name='assetmaintenancestatus',
            name='maintenance_expire_on',
            field=models.DateField(default=datetime.date(2023, 11, 14)),
        ),
        migrations.AlterField(
            model_name='assetmaintenancestatus',
            name='maintenance_reward_status',
            field=models.IntegerField(choices=[(0, 'Not Claimed'), (1, 'Claim In Progress'), (2, 'Approved'), (3, 'Rejected'), (4, 'Pre-Approved')], default=0),
        ),
    ]
