# Generated by Django 4.2.7 on 2023-12-04 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_alter_assetmaintenancestatus_maintenance_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintenancestatus',
            name='maintenance_expire_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
