# Generated by Django 4.1 on 2024-04-04 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_alter_assetmaintenancestatus_maintenance_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintenancestatus',
            name='maintenance_started_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
