# Generated by Django 4.2.7 on 2023-12-06 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=100)),
                ('title_id', models.CharField(max_length=13)),
                ('activity', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'protocol_transactions',
            },
        ),
    ]
