# Generated by Django 4.2.7 on 2023-12-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoltransaction',
            name='account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='protocoltransaction',
            name='title_id',
            field=models.CharField(max_length=20),
        ),
    ]
