# Generated by Django 4.1 on 2022-10-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='net',
            field=models.CharField(choices=[(1, 'MAIN'), (2, 'BETA'), (3, 'TEST')], max_length=15),
        ),
    ]
