# Generated by Django 4.1 on 2022-11-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_data_alter_notification_net'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
    ]
