# Generated by Django 3.2.15 on 2022-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='otp_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
