# Generated by Django 3.2.15 on 2022-09-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220908_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
