# Generated by Django 3.2.15 on 2022-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_device_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='request_mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
