# Generated by Django 3.2.15 on 2022-09-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_request_mobile_device_requested_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='otp_verification_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
