# Generated by Django 4.1 on 2022-09-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_device_otp_verification_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='country_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
