# Generated by Django 4.1 on 2022-09-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_device_country_code_alter_device_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mobile',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='requested_mobile',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
