# Generated by Django 4.1 on 2023-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_device_country_code_alter_device_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
