# Generated by Django 4.1 on 2024-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_is_deleted_device_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
