# Generated by Django 4.1 on 2024-02-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_device_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
