# Generated by Django 4.1 on 2024-02-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
