# Generated by Django 4.1 on 2024-02-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_account_is_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
