# Generated by Django 4.2.7 on 2023-11-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0012_alter_assetmaintenancestatus_maintenance_claim_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LocationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('pincode', models.CharField(default='000000', max_length=6)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalMaintenanceModel',
            fields=[
            ],
            options={
                'verbose_name': 'Approval Maintenance Claim',
                'verbose_name_plural': 'Approval Maintenance Claim',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('asset.assetmaintenancestatus',),
        ),
        migrations.CreateModel(
            name='PreApprovalMaintenanceRequestModel',
            fields=[
            ],
            options={
                'verbose_name': 'Pre-Approval Maintenance Claim Request',
                'verbose_name_plural': 'Pre-Approval Maintenance Claim Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('asset.assetmaintenancestatus',),
        ),
        migrations.CreateModel(
            name='PreRewardRequestModel',
            fields=[
            ],
            options={
                'verbose_name': 'Pre-Approval Maintenace Reward',
                'verbose_name_plural': 'Pre-Approval Maintenace Reward',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('asset.assetmaintenancestatus',),
        ),
        migrations.CreateModel(
            name='RewardRequestModel',
            fields=[
            ],
            options={
                'verbose_name': 'Approval Maintenace Reward',
                'verbose_name_plural': 'Approval Maintenace Rewards',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('asset.assetmaintenancestatus',),
        ),
    ]
