# Generated by Django 4.2.7 on 2023-12-04 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_contractdata_contractfund_withdrawfund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdata',
            name='algo_balance_func',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contractdata',
            name='contract_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contractdata',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contractdata',
            name='unlock_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contractdata',
            name='unlock_balance_func',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contractdata',
            name='unlock_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractdata',
            name='usdc_balance_func',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contractdata',
            name='usdc_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractfund',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.contractdata'),
        ),
        migrations.AddField(
            model_name='withdrawfund',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.contractdata'),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='algo_balanace',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='usdc_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='contractdata',
            table='contract_data',
        ),
    ]
