# Generated by Django 4.2.7 on 2023-12-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_contractdata_algo_balance_func_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('maintenance_pool_total', models.FloatField()),
                ('total_claimed', models.IntegerField()),
                ('titles_in_maintain_total', models.IntegerField()),
                ('titles_maintained_total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
    ]
