# Generated by Django 4.2.7 on 2023-12-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_consoledata_alter_feedback_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractdata',
            old_name='algo_balanace',
            new_name='algo_balance',
        ),
    ]
