# Generated by Django 4.2.7 on 2023-12-18 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_alter_assetmaintenancestatus_maintenance_expire_on'),
        ('adminpanel', '0005_rename_algo_balanace_contractdata_algo_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleUnderMaintenance',
            fields=[
            ],
            options={
                'verbose_name_plural': '0 Title Under Maintenance',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('asset.assetmaintenancestatus',),
        ),
        migrations.AlterModelOptions(
            name='approvalmaintenancemodel',
            options={'verbose_name': 'Approval Maintenance Claim', 'verbose_name_plural': '2 Approval Maintenance Claim'},
        ),
        migrations.AlterModelOptions(
            name='approvedclaimmodel',
            options={'verbose_name': 'Approved Claim Maintenance ', 'verbose_name_plural': '4 Approved Claim Maintenance'},
        ),
        migrations.AlterModelOptions(
            name='approvedrewardmodel',
            options={'verbose_name': 'Approved Reward Maintenance Reward', 'verbose_name_plural': '4 Approved Reward Maintenance Rewards'},
        ),
        migrations.AlterModelOptions(
            name='consoledata',
            options={'verbose_name_plural': 'Console Records'},
        ),
        migrations.AlterModelOptions(
            name='contractdata',
            options={'verbose_name_plural': 'Contract Balance'},
        ),
        migrations.AlterModelOptions(
            name='preapprovalmaintenancerequestmodel',
            options={'verbose_name': 'Pre-Approval Maintenance Claim Request', 'verbose_name_plural': '1 Pre-Approval Maintenance Claim Requests'},
        ),
        migrations.AlterModelOptions(
            name='prerewardrequestmodel',
            options={'verbose_name': 'Pre-Approval Maintenace Reward', 'verbose_name_plural': '1 Pre-Approval Maintenace Reward'},
        ),
        migrations.AlterModelOptions(
            name='rejectedclaimmodel',
            options={'verbose_name': 'Rejected Claim Maintenance ', 'verbose_name_plural': '3 Rejected Claim Maintenance'},
        ),
        migrations.AlterModelOptions(
            name='rejectedrewardmodel',
            options={'verbose_name': 'Rejected Reward Maintenance Reward', 'verbose_name_plural': '3 Rejected Reward Maintenance Rewards'},
        ),
        migrations.AlterModelOptions(
            name='rewardrequestmodel',
            options={'verbose_name': 'Approval Maintenace Reward', 'verbose_name_plural': '2 Approval Maintenace Rewards'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
