# Generated by Django 4.2.7 on 2023-11-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TopTokenizedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(max_length=10)),
                ('market_price', models.IntegerField(default=0)),
                ('vol', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.brand')),
            ],
            options={
                'db_table': 'top_tokenized_assets',
            },
        ),
    ]
